env:
  # OrangeFox Sync Repository
  FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

  # Config
  CONFIG: config.sh

  # Telegram
  TG_CHAT_ID: ENCRYPTED[!8f077d9c656659ad446170ed3f0eb5572693c20bdcd939df74ad01273733210bde452d2825bca9a44017ea2b5ce43db4!]
  TG_TOKEN: ENCRYPTED[!99f9383406414769aadc9fd9880697bac7a8b1db5613f479b9487790e68e87595f853c5621cd9ff1bff5e66c57732c88!]

  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
    image: ghcr.io/sushrut1101/docker:arch
    cpu: 8
    memory: 20G

  Checks_script:
    - bash -c "$(curl -sL https://raw.githubusercontent.com/fukiame/cirrus_ofox/main/scripts/checks.sh)"

  Sync_script:
    - bash -c "$(curl -sL https://raw.githubusercontent.com/fukiame/cirrus_ofox/main/scripts/sync.sh)"

  Build_script:
    - bash -c "$(curl -sL https://raw.githubusercontent.com/fukiame/cirrus_ofox/main/scripts/build.sh)"

  Upload_script:
    - export TIMEOUT=43200 # Link timeout (in minutes)
    - bash -c "$(curl -sL https://raw.githubusercontent.com/fukiame/cirrus_ofox/main/scripts/upload.sh)"
